name: Infrastructure Check 


on: 
  push: 
    branches: 
    - main 

jobs: 
  check: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
      - name: Run Terraform Validate 
        run: terraform validate
  deploy:
    name: Deploy actions
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install node
        run: npm install
  